### ISSUE TITLE
Program is reopening when it closed

### ISSUE THREAD

**Issue by ygz213** [iDCoded/D-Pad#5]
**Describe the bug**

Program is reopening when I close it. (for once)

**To Reproduce**

1. Run program
2. Close
3. See bug

**Expected behavior**

Program should not reopen.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

Problem is here:

```
(main.py/line 455-456)
    # Running mainloop
    ROOT.mainloop()
```
and

```
(main.py/line 641-642)
# Running mainloop
ROOT.mainloop()
```

Program is twice launching by `ROOT.mainloop()`s

**Comment by dhruvnnd** [comment]
I have fixed this issue. 
It is so silly that I did not look into it and this is such a bizarre bug. 

I really appreciate you for pointing this out. Thanks a lot.
