### ISSUE TITLE
Text formatting is not working

### ISSUE THREAD

**Issue by ygz213** [iDCoded/D-Pad#8]
**Describe the bug**

`Bold`, `Italics` and `Underline` buttons don't anything.

**To Reproduce**

1. Run program
2. Click to one of them

**Expected behavior**

App should do formatting (I think formatting in `.txt` files is impossible)

**Desktop (please complete the following information):**

 - OS: Windows
 - Version: 10

**Additional context**

`_tkinter.TclError: text doesn't contain any characters tagged with "sel"` on every button's `text_tags = text_field.tag_names(SEL_FIRST)`

**Comment by dhruvnnd** [comment]
![image](https://user-images.githubusercontent.com/65074550/127960224-2307f270-21de-4aac-b8c9-601229dcf815.png)
It is working for me. 

What version of the Application are you using?

**Comment by ygz213** [comment]
v1.1.1. What version of Python are you using? (I am using 3.9.6)

**Comment by dhruvnnd** [comment]
> v1.1.1. What version of Python are you using? (I am using 3.9.6)

#### Application Version : **Latest** (`v1.1.1`)
#### Python Version : `3.9.5`

---
There is no error for me when I try the Text Formatting. The text gets formatted perfectly.

**Comment by ygz213** [comment]
Sorry for being late

![IMG_20210803_111943_951](https://user-images.githubusercontent.com/77006222/128040616-a4dd9dca-84f6-4be4-9750-8e8a1b058a29.jpg)
![IMG_20210803_112306_092](https://user-images.githubusercontent.com/77006222/128040653-e331a10e-4846-4cdb-ac32-a6d86711ed81.jpg)

**Comment by dhruvnnd** [comment]
Try running the `.exe` application. It should work if you run the Application.

---
### Development
- Do you have Tkinter installed? 
- Are you selecting the text before formatting it?
    - **Currently, text can be formatted only by selecting it. So you will have to highlight the text you wish to format and then click on the buttons.**

**Comment by ygz213** [comment]
I could texts formatted by selecting but formatted texts is forgetting by app after reopen the file.

**Comment by dhruvnnd** [comment]
> I could texts formatted by selecting but formatted texts is forgetting by app after reopen the file.

That is because it is a **Text** file, if we edit **Markdown** files, it would remember the formatting. The text formatting stays only while the app is running. 
This was of course looked by me, and will be updated in the future in upcoming versions.
